name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: cargo build --release

      - name: Get binary name
        id: get_binary_name
        run: |
          REPO_NAME="${{ github.repository }}"
          REPO_NAME_ONLY="${REPO_NAME##*/}"

          BINARY_NAME="${REPO_NAME_ONLY//-/_}"
          echo "binary_name=$BINARY_NAME" >> $GITHUB_OUTPUT

      - name: Upload release
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.get_binary_name.outputs.binary_name }}_release
          path: target/release/${{ steps.get_binary_name.outputs.binary_name }}
